%% Figure stats
for met = 1:length(metric_list)
    mtname = metric_list{met};
    mtname = strcat(mtname,'_interp');
    metric_interp = tstatps.(mtname);
    %
    fig = figure;    
    select_freqs = [2 5 11 24 25 27 41 43 46 47];
    for freq = 1:size(metric_interp,2)          
           metric_tmpe = metric_interp(:,freq);
            template            = load('axes.mat');
            currentAxes         = template.axes;
            patch(currentAxes,...
                'Faces',Faces, ...
                'Vertices',Vertices, ...
                'FaceVertexCData',metric_tmpe, ...
                'FaceColor','interp', ...
                'EdgeColor','none', ...
                'AlphaDataMapping', 'none', ...
                'EdgeColor',        'none', ...
                'EdgeAlpha',        1, ...
                'BackfaceLighting', 'lit', ...
                'AmbientStrength',  0.5, ...
                'DiffuseStrength',  0.5, ...
                'SpecularStrength', 0.2, ...
                'SpecularExponent', 1, ...
                'SpecularColorReflectance', 0.5, ...
                'FaceLighting',     'gouraud', ...
                'EdgeLighting',     'gouraud', ...
                'FaceAlpha',.99);
            axis off;
            rotate3d on;            
            axis tight;
            view(90,90)
            max_val = max(abs(metric_tmpe));
            currentAxes.CLim = [(-max_val-0.01) (max_val+0.01)];
            colormap(bipolar(201, 0.3))  
            plot_tmpe = subplot(6,8,freq,currentAxes);
            % copyobj(currentAxes,plot_tmpe);        
    end
    saveas(fig,strcat(mtname,'.fig'));
    close(fig)
end